### ISSUE TITLE
Event Tracking 

### ISSUE THREAD

**Issue by aakashtandel** [beacon-biosignals/beacon-biosignals-netlify-cms#24]
### 1) Form Submissions - Partner with Us
![Screen Shot 2020-08-24 at 3 44 20 PM](https://user-images.githubusercontent.com/8173223/91190548-b3edbc80-e6c1-11ea-8faf-65d3c3f50d97.png)

When a user successfully submits the Partner With Us form execute the following code, dynamically replacing the page URL in brackets:
```
<script>
  window.dataLayer = window.dataLayer || [];
  dataLayer.push({
    'event': 'interaction',
    'event_category': 'Form Submissions', 
    'event_action': 'Partner with Us', 
    'event_label': '{{Page URL}}'
  });
</script>
```

Standard Page URL example:
```
<script>
  window.dataLayer = window.dataLayer || [];
  dataLayer.push({
    'event': 'interaction',
    'event_category': 'Form Submissions', 
    'event_action': 'Partner with Us', 
    'event_label': 'https://www.beacon.bio/partnerships'
  });
</script>
```

### 2) Form Submissions - Neurologists
![Screen Shot 2020-08-24 at 3 44 26 PM](https://user-images.githubusercontent.com/8173223/91190557-b5b78000-e6c1-11ea-827a-87867d2d99a0.png)

When a user successfully submits the Neurologists form execute the following code, dynamically replacing the page URL in brackets:
```
<script>
  window.dataLayer = window.dataLayer || [];
  dataLayer.push({
    'event': 'interaction',
    'event_category': 'Form Submissions', 
    'event_action': 'Neurologists', 
    'event_label': '{{Page URL}}'
  });
</script>
```

Standard Page URL example:
```
<script>
  window.dataLayer = window.dataLayer || [];
  dataLayer.push({
    'event': 'interaction',
    'event_category': 'Form Submissions', 
    'event_action': 'Neurologists', 
    'event_label': 'https://www.beacon.bio/neurologists'
  });
</script>
```

### 3) Homepage - Partnerships Learn More
![Screen Shot 2020-08-24 at 3 52 20 PM](https://user-images.githubusercontent.com/8173223/91190604-c23bd880-e6c1-11ea-9d2e-e753b96d61a2.png)

Add the following inline data attribute to the “Learn More” button:
```
data-track-gtm="Homepage|Partnerships|Learn More Button"
```

### 4) Career Outbound Links
![Screen Shot 2020-08-24 at 3 53 57 PM](https://user-images.githubusercontent.com/8173223/91190625-c8ca5000-e6c1-11ea-8499-4f25346286d8.png)

Add the following inline data attributes to each job link, dynamically replacing the link text and link URL:
```
data-track-gtm="Career Links|{{Link Text}}|{{Link URL}}"
```

Ops Engineer example: 
```
data-track-gtm="Career Links|Ops Engineer|https://boards.greenhouse.io/beaconbiosignals/jobs/4122416003"
```

### 5) Top Navigation 
![Screen Shot 2020-08-24 at 3 58 23 PM](https://user-images.githubusercontent.com/8173223/91190732-e5ff1e80-e6c1-11ea-95d7-a1ff80bac1df.png)

Add the following inline data attributes to the top navigation items:
Beacon Biosignals Logo:
```
data-track-gtm="Top Navigation|Logo Homepage"
```

Our Team:
```
data-track-gtm="Top Navigation|Our Team"
```

Careers: 
```
data-track-gtm="Top Navigation|Careers"
```

Neurologists:
```
data-track-gtm="Top Navigation|Neurologists"
```

Partner with Us: 
```
data-track-gtm="Top Navigation|Partner with Us"
```

Login: 
```
data-track-gtm="Top Navigation|Login"
```

### 6) Footer Navigation 
![Screen Shot 2020-08-24 at 4 01 29 PM](https://user-images.githubusercontent.com/8173223/91190646-ce279a80-e6c1-11ea-99dd-171e3d53bd59.png)

Add the following inline data attributes to footer navigation items:
Beacon Biosignals Logo:
```
data-track-gtm="Footer Navigation|Logo Homepage"
```

Privacy Policy: 
```
data-track-gtm="Footer Navigation|Privacy Policy"
```

Terms of Use: 
```
data-track-gtm="Footer Navigation|Terms of Use"
```

**Comment by davist11** [comment]
This is ready for your review: https://deploy-preview-25--eloquent-lamport-82018f.netlify.app/

**Comment by aakashtandel** [comment]
Perfect to a T
